main : main.o poketudiant.o

		gcc main.o poketudiant.o -o main

main.o : main.c poketudiant.o

		gcc -c main.c -o main.o

poketudiant.o : poketudiant.c  poketudiant.h 

		gcc -c poketudiant.c -o poketudiant.o